#!/bin/sh

BUN_PATH=bun

if [ -f ~/.bun/bin/bun ]; then
  BUN_PATH=~/.bun/bin/bun
elif [ -f /usr/local/bin/bun ]; then
  BUN_PATH=/usr/local/bin/bun
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(json|ts)$' | tr '\n' ' ')

if [ -n "$STAGED_FILES" ]; then
  if command -v eslint_d &> /dev/null; then
    eslint_d --cache $STAGED_FILES
  else
    $BUN_PATH eslint --cache $STAGED_FILES
  fi
fi
