name: generate-pages

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '**/*.js'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install lcov
        run: apt-get update && apt-get install -y lcov

      - name: Build pages
        run: |
          bun install
          bun run doc
          bun run test:coverage

      - name: Combine docs and coverage
        run: |
          mkdir -p combined/docs combined/coverage
          cp -r docs/* combined/docs/
          cp -r coverage-report/* combined/coverage/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: combined
